# Generated by Django 4.0.1 on 2022-01-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('PRODUCT', 'question_product'), ('DELIVERY', 'question_delievery'), ('REFUND', 'question_refund')], max_length=10)),
                ('importance', models.IntegerField(choices=[(1, 'Emergency'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Trivial')])),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question')),
            ],
        ),
    ]
