# Generated by Django 4.0.1 on 2022-01-13 15:37

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='attached_file',
            field=models.FileField(blank=True, upload_to=pybo.models.Question.attached_file_path),
        ),
        migrations.AddField(
            model_name='question',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Emergency'), (2, 'High'), (3, 'Normal'), (4, 'Low'), (5, 'Trivial')], default=3),
        ),
    ]
